version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - redis:/data
  # app:
  #   build: .
  #   environment:
  #     PORT: 4000
  #     DATABASE_URL: postgresql://postgres:password@postgres
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "4000:4000"
volumes:
  postgres:
  redis:
